### ISSUE TITLE
フレンド申請を受領すると自分自身がフレンドになってしまう

### ISSUE THREAD

**Issue by rom6621** [Haebeal/datti-api#119]
GET /friends/pendings で取得した受領中のフレンド申請を POST /users/{uid}/requests で承認した際、GET /friends のレスポンスが対象ユーザーではなく自分自身になってしまう。
なお、この事象の後に対象ユーザーに POST /users/{uid}/requests を送っても申請中とはならないため、GET /friends がバグってる可能性有。

<img width="1369" alt="スクリーンショット 2024-04-14 22 25 23" src="https://github.com/Haebeal/datti-api/assets/56793273/910a4741-2e7f-415f-97d1-3b60f15068e9">

**Comment by nasbeeeeeem** [comment]
関数GetFriends()で生成するSQLに誤りがあったので修正しました。

**Comment by rom6621** [comment]
適切にフレンド承認されること確認できました！

![Image](https://github.com/Haebeal/datti-api/assets/56793273/1107124c-82a2-4efa-b1b0-ba687579e67b)
