### ISSUE TITLE
GET /users のemailをリクエストボディからオプショナルなクエリパラメーターに変更して欲しい

### ISSUE THREAD

**Issue by rom6621** [Haebeal/datti-api#120]
GETメソッドにリクエストボディは付与できないため、クエリパラメーターへの変更をお願いします。

<img width="1000" alt="スクリーンショット 2024-04-14 22 45 40" src="https://github.com/Haebeal/datti-api/assets/56793273/b761f1cf-d24d-4de4-8cd3-e3ffa92593a1">

**Comment by nasbeeeeeem** [comment]
API仕様書とGET:/users に対応するハンドラ関数を修正しました。
クエリパラメータとしてemailに値を指定する形式です。
hogeに指定した値でDBへLike検索が実行されます
`/users/?email=hoge`

**Comment by rom6621** [comment]
実装の中で不都合あったらまた連携しますー
[![LGTMeow](https://lgtm-images.lgtmeow.com/2022/01/10/22/2eec706d-f1ea-4756-9fb5-00cffc5ed09b.webp)](https://lgtmeow.com)
