### ISSUE TITLE
フレンド解除時に相手からの状態はどうなるか

### ISSUE THREAD

**Issue by rom6621** [Haebeal/datti-api#121]
DELETE /friends/{uid} リクエスト時はお互いのリクエストが消える認識であってるでしょうか？
もし片方のリクエストのみを削除する場合、申請待ちになってしまうと思うため念の為聞いた次第です。

**Comment by nasbeeeeeem** [comment]
以下のSQLが実行され、お互いの申請状態を削除することでフレンドの関係を解除してます。
`DELETE FROM "friends" AS "friend" WHERE (uid = '自分のUID' AND friend_uid = '解除対象のユーザのUID') OR (uid = '解除対象のユーザのUID' AND friend_uid = '自分のUID')`
DELETE /friends/{uid}ではお互いの申請を削除しているため片方が申請待ちになることは無い認識です。

**Comment by rom6621** [comment]
[![LGTMeow](https://lgtm-images.lgtmeow.com/2022/03/05/00/96228566-ea11-416b-9521-c4b96e6e9775.webp)](https://lgtmeow.com)
