### ISSUE TITLE
GET /usersにおけるユーザー情報取得時に相手に対するステータスを取得することはできるか

### ISSUE THREAD

**Issue by rom6621** [Haebeal/datti-api#125]
フレンド申請画面を作成しているのですが、この時に「フレンド」「申請中」「受領中」のような形で相手に対するステータスを表示できればと考えています。
この実装をエンドポイントで
イメージ的には GET /users/hoge で
```json
{
  "uid": "stringstringstringstringstri",
  "name": "string",
  ...
  "status": "friend" | "applying" | "requesting" | "none"
}
```
のようなリクエストが返ってくる感じ。

<img width="758" alt="スクリーンショット 2024-04-21 14 11 21" src="https://github.com/Haebeal/datti-api/assets/56793273/9e532947-0fcc-450b-9c69-ff0604638e5a">

**Comment by nasbeeeeeem** [comment]
GET /users/{userId}/{status}で実装しようと考えています。
上記のAPIにリクエストを送ったユーザーと{userId}で指定したユーザーのフレンド関係の状態を返すようなイメージです
