### ISSUE TITLE
banks廃止に伴うOpenAPIの更新が反映されていない

### ISSUE THREAD

**Issue by rom6621** [Haebeal/datti-api#129]
#124 の内容がOpenAPIに反映されていないため、修正お願いします。

**Comment by nasbeeeeeem** [comment]
delete /bankの定義自体が削除できていませんでした。
actions自体は問題ないと思います。
![Uploading スクリーンショット 2024-05-01 18.39.10.png…]()

**Comment by rom6621** [comment]
#133 で実装を行うためClose
