### ISSUE TITLE
ステータスが取れない等のレスポンスとOpenAPIとの差分が存在する

### ISSUE THREAD

**Issue by rom6621** [Haebeal/datti-api#147]
以下のエンドポイントで差分が発生しています。
修正お願いいたします。

- GET /friends
<img width="1414" alt="スクリーンショット 2024-06-01 22 39 15" src="https://github.com/Haebeal/datti-api/assets/56793273/5fb4ceae-1832-4f0c-8c3c-ddafd6b9350b">

- GET /groups/{groupId}/members
<img width="853" alt="スクリーンショット 2024-06-01 22 37 36" src="https://github.com/Haebeal/datti-api/assets/56793273/0f28fc51-4c26-4f26-aa10-56a3d6ea141e">

**Comment by nasbeeeeeem** [comment]
Duplicate of #149
