### ISSUE TITLE
ユーザーのID項目を`userId`に統一してほしい

### ISSUE THREAD

**Issue by rom6621** [Haebeal/datti-api#187]
### 対象メソッド

- [x] GET
- [x] POST
- [x] PUT
- [x] DELETE

### 対象エンドポイント

全般

### 詳細内容

- レスポンスやリクエストボディのユーザーID項目が`uid`のところと`userId`が存在するので, `userId`に統一してほしいです

**Comment by nasbeeeeeem** [comment]
#179 にて対応済みです
Duplicate of #179
