### ISSUE TITLE
Paymentスキーマの`paid_to`と`paid_by`にstatusを付与してほしい

### ISSUE THREAD

**Issue by rom6621** [haebeal/datti-api#188]
### 対象メソッド

- [x] GET
- [ ] POST
- [ ] PUT
- [ ] DELETE

### 対象エンドポイント

/payments

### 詳細内容

- `user`に`status`だけ付与されていないのは不自然なので、追加するようお願いします
- 他の項目についてもユーザー関連のものは`userId`だけを返すか、`User`スキーマ丸々返すかのどちらかにするように徹底おねがいします

**Comment by nasbeeeeeem** [comment]
モノレポに移行したためクローズ
