### ISSUE TITLE
グループメンバー追加時のレスポンスがOpenAPIと異なる

### ISSUE THREAD

**Issue by rom6621** [Haebeal/datti-api#196]
### 対象メソッド

- [ ] GET
- [x] POST
- [ ] PUT
- [ ] DELETE

### 対象エンドポイント

/groups/{groupId}/members

### 詳細内容

以下の通り、実際のレスポンスとOpenAPIに記載されているレスポンスが剥離しています。

![Image](https://github.com/Haebeal/datti-api/assets/56793273/d3c0a070-a53b-48cb-b122-eeea37567a20)
![Image](https://github.com/Haebeal/datti-api/assets/56793273/6fcfcc10-b8b2-4f97-a8fa-9e0d7cbc2177)

そもそものレスポンス設計を変えるのもありだと思うので、以下のような誰が追加されたかをトーストで表示させる実装が可能なようにレスポンスの実装をお願いいたします。
![Image](https://github.com/Haebeal/datti-api/assets/56793273/4f512a1b-1170-4b2c-94f0-0213f8d3056a)

**Comment by nasbeeeeeem** [comment]
openAPIを正しく修正すれば、このようなレスポンスが返却されます。
この設計ではトースト表示に問題があれば教えてください。
```
{
  "groupId": "string"
  "name": "string"
  "members": [
    {
      "userId": "stringstringstringstringstri",
      "name": "string",
      "email": "string",
      "photoUrl": "string",
      "status": "me"
    }
  ]
}
```

**Comment by rom6621** [comment]
@nasbeeeeeem 
このレスポンスだとメンバー全員が返されてしまっていて誰が追加されたかがわからないのでそこがわかるようなレスポンスにしてほしいです

**Comment by rom6621** [comment]
@nasbeeeeeem 
解決確認できたのでクローズで大丈夫です！

![Image](https://github.com/Haebeal/datti-api/assets/56793273/79f3f394-e678-4469-b154-333ed1037810)
